name: "Paratco hosting"
description: "Deploy static websites to Paratco hosting"
author: "Paratco"
branding:
  icon: cloud
  color: blue
inputs:
  host:
    description: "Hosting hostname"
    required: true
    default: ""
  token:
    description: "Hosting API token"
    required: true
    default: ""
  file:
    description: "Zip file to be uploaded"
    required: true
    default: ""
  deploy:
    description: "Whether to deploy uploaded file or not"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
