name: "Zip Deploy"
description: "Deploy static websites to Paratco hosting."
author: "Paratco"
branding:
  icon: cloud
  color: blue
inputs:
  api:
    description: "API URL"
    required: true
    default: ""
  file:
    description: "Zip file"
    required: true
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
