name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run my action
        uses: ./
        with:
          host: "https://postman-echo.com"
          token: "fdGYUuB0196WPR2cPIR8P2L0XMZPv2bq5xPlNYRDqRP1u9wwYPDF5T6Yh3&yGfR3"
          tag: "1.2.3"
          deploy: "true"
          file: sample/app.zip
